const SIGN_IN = 'USER/SIGN_IN';
const SIGN_OUT = 'USER/SIGN_OUT';
const UPDATE_USER = 'USER/UPDATE_USER';
const UPDATE_USER_RBAC = 'USER/UPDATE_USER_RBAC';

export default {
  SIGN_IN,
  SIGN_OUT,
  UPDATE_USER,
  UPDATE_USER_RBAC,
};
export {
  SIGN_IN,
  SIGN_OUT,
  UPDATE_USER,
  UPDATE_USER_RBAC,
};
