name: build-source

on: push

jobs:
  build-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: yarn
      - name: Build source
        run: yarn build
